### ISSUE TITLE
Schematics: TODO

### ISSUE THREAD

**Issue by AnthonyAMC** [DenizenScript/Denizen-For-Bukkit#1365]
One issue page for schematic related... issues

- [x] Rotation and angle arguments
- [x] Flipping/mirror with ability to specify which axis to flip around.
- [x] File argument for save and load
- [x] Container blocks
- [x] noair argument
- [x] origin fixing

Tags are nice too!
- [ ] `<schematic[<name>].locations>` should return the list of location objects, for doing things with
- [ ] `<schematic[<name>].materials>`

**Comment by CorporalBruno** [comment]
yas container blocks super important. this is like fire for me right now. thanks for fixing.

**Comment by Mickket** [comment]
noair switch is not working for schematic pasting.

**Comment by CorporalBruno** [comment]
container blocks now work and banners, and all other entities. thanks McMonkey.

**Comment by mcmonkey4eva** [comment]
Noair argument added to dev build 558

**Comment by mcmonkey4eva** [comment]
Filename argument added for dev build 558 as well

**Comment by CorporalBruno** [comment]
I found an additional bug regarding schematic command.

chain mail armor is wiped clean as normal iron armor after a paste. enchantments and all.

**Comment by GomaTerzu** [comment]
Could you please add a working rotate?

**Comment by mcmonkey4eva** [comment]
Ima probably be attacking schematics sometime soon... made a self-note for it.

**Comment by calico-kid** [comment]
fix origin location for the pastes and make them paste less broken and out of place.
thanks mrmonkey

**Comment by mcmonkey4eva** [comment]
Got all the schematic commands done finally :)
