### ISSUE TITLE
Denizen 1.0.5 on Minecraft 1.14 Meta-Issue

### ISSUE THREAD

**Issue by mcmonkey4eva** [DenizenScript/Denizen-For-Bukkit#1951]
Hey! The first Denizen builds compatible with Minecraft 1.14 are released on the dev releases page here: https://ci.citizensnpcs.co/job/Denizen_Developmental/ as version 1.0.5!

Please use this issue thread to post any issues you encounter with the basic updating process!

Things that need testing:
- [x] Midi playback accuracy
- [x] Entity sitting
- [x] Tipped arrows - arrow entity handling is a bit broken (applying unwanted potion tips - actually a spigot issue so this is fine)
- [x] hide_entity mechanisms
- [x] Fishing
- [x] Opening villager trades - broken.
- [x] dPlayer.vision mechanism
- [x] player.chunk_loaded tag
- Also just functionality in general.

Known broken (need fixing):
- [ ] Light command.
- [ ] Entity flags/script autoremoval, entity despawn event, glow command autoclear (Entity despawn tracking is broken)
- [ ] ChunkLoad command no longer keeps a chunk forcibly loaded (due to removal of cancellation from the ChunkUnloadEvent)
- [ ] OpenTrades command is non-functional due to the new trading system in 1.14

Strongly advise you **do not use entity flags or entity scripts** until that issue is fixed, as they will "work" but flood your saves files.

**Comment by mcmonkey4eva** [comment]
Have found a rather major issue:
Any block reading completely fails when tag timeouts are enabled. Likely related to increased world handling complexity in 1.14.

**EDIT:** Resolved by https://github.com/DenizenScript/Denizen-For-Bukkit/commit/952089baeae912745e0bc2953db9b7a1a31952e2

**Comment by mcmonkey4eva** [comment]
Testing notes:
- Midi seems fine. Denizen.mid sounds about correct.
- Tipped arrows: something seems wrong. `/ex spawn arrow` will spawn an arrow with some form of tipped effect going. Doesn't look like the potioneffects property is applying itself to the arrow so unsure what went wrong.
- Sitting property works fine.
- Hide_Entity works fine.
- Opening a custom trade works however the trade window does not function (you cannot actually trade anything).
Trying to open a `Trader` entity's trade list results in:
```
java.lang.IllegalArgumentException: Can't open merchant CraftWanderingTrader
org.bukkit.craftbukkit.v1_14_R1.entity.CraftHumanEntity.openMerchant(CraftHumanEntity.java:560)
net.aufdemrand.denizen.scripts.commands.player.OpenTradesCommand.execute(OpenTradesCommand.java:85)
net.aufdemrand.denizencore.scripts.commands.CommandExecuter.execute(CommandExecuter.java:180)
```
- Vision mechanism works, though `spider` and `cave_spider` produce exactly the same visual results.
- Chunk_loaded tag works fine
- Fishing works but fishing trait is dumb as usual

**Comment by SlimeDog** [comment]
Spigot 1.14 latest (2203)
Citizens 2.0.25-build1661
Denizen 1.0.5-b773-DEV

EventExceptions on server start-up
```
[08:44:24] [Server thread/ERROR]: Could not pass event ChunkUnloadEvent to Denizen v1.0.5-SNAPSHOT (build 773-DEV)
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.14.jar-2019-04-26-0843:git-Spigot-47463c2-6de3aa1]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.jar-2019-04-26-0843:git-Spigot-47463c2-6de3aa1]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:508) ~[spigot-1.14.jar-2019-04-26-0843:git-Spigot-47463c2-6de3aa1]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:493) ~[spigot-1.14.jar-2019-04-26-0843:git-Spigot-47463c2-6de3aa1]
        at net.minecraft.server.v1_14_R1.PlayerChunkMap.lambda$12(PlayerChunkMap.java:333) ~[spigot-1.14.jar-2019-04-26-0843:git-Spigot-47463c2-6de3aa1]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) [?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) [?:?]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [spigot-1.14.jar-2019-04-26-0843:git-Spigot-47463c2-6de3aa1]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [spigot-1.14.jar-2019-04-26-0843:git-Spigot-47463c2-6de3aa1]
        at net.minecraft.server.v1_14_R1.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:438) [spigot-1.14.jar-2019-04-26-0843:git-Spigot-47463c2-6de3aa1]
        at net.minecraft.server.v1_14_R1.ChunkProviderServer.runTasks(ChunkProviderServer.java:163) [spigot-1.14.jar-2019-04-26-0843:git-Spigot-47463c2-6de3aa1]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:901) [spigot-1.14.jar-2019-04-26-0843:git-Spigot-47463c2-6de3aa1]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:885) [spigot-1.14.jar-2019-04-26-0843:git-Spigot-47463c2-6de3aa1]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(SourceFile:99) [spigot-1.14.jar-2019-04-26-0843:git-Spigot-47463c2-6de3aa1]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:868) [spigot-1.14.jar-2019-04-26-0843:git-Spigot-47463c2-6de3aa1]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:802) [spigot-1.14.jar-2019-04-26-0843:git-Spigot-47463c2-6de3aa1]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```
Same with Citizens 2.0.25-b1663

**Comment by mcmonkey4eva** [comment]
Can you find the rest of that error message? That's very incomplete.

**Comment by SlimeDog** [comment]
Just restarted...
Spigot 1.14 latest (2203)
Citizens 2.0.25-build1663
Denizen 1.0.5-b773-DEV
Here are all Citizens and Denizen log lines:
https://one.denizenscript.com/haste/54087

**Comment by mcmonkey4eva** [comment]
@SlimeDog I moved your log to a pastebin (to fit on the page sanely)

Anyway, looks like Spigot removed cancellation from the ChunkUnloadEvent in 1.14 ... eck.
Fixed handling of that in https://github.com/DenizenScript/Denizen-For-Bukkit/commit/7219996c818332d0ba504c65675beb2f933aa6ec and build DEV-774+

However this means the chunkload command is now broken.

**Comment by SlimeDog** [comment]
Thanks. And on it goes...

**Comment by SlimeDog** [comment]
Confirmed fixed in b774.

**Comment by waterquarks** [comment]
https://one.denizenscript.com/paste/54090
when trying to open any player's inventory

**Comment by mcmonkey4eva** [comment]
The arrow potion issue seems to actually be a Spigot issue, not on our end.

**Comment by SlimeDog** [comment]
Spigot 1.14 (2235)
Citizens 2.0.25-SNAPSHOT (build 1669)
Denizen 1.0.5-SNAPSHOT (build 775-DEV)

Probably a change in Spigot today, but on server start-up
```
[06:43:07] [Server thread/INFO]: [Denizen] Enabling Denizen v1.0.5-SNAPSHOT (build 775-DEV) 
[06:43:07] [Server thread/WARN]: [Denizen] -------------------------------------
[06:43:07] [Server thread/WARN]: [Denizen] This build of Denizen was built for a different Spigot revision! This may potentially cause issues. If you are experiencing trouble, update Denizen and Spigot both to latest builds! If this message appears with both Denizen and Spigot fully up-to-date, contact the Denizen team (via GitHub, Spigot, or Discord) to request an update be built. 
[06:43:07] [Server thread/WARN]: [Denizen] -------------------------------------
[06:43:07] [Server thread/INFO]: +> [Denizen] Initializing Denizen Core v1.40-SNAPSHOT (Build 252), implementation for Bukkit version 1.0.5-SNAPSHOT (build
                   775-DEV) ^[[m 
[06:43:07] [Server thread/INFO]: +> [Denizen] +-------------------------+
[06:43:07] [Server thread/INFO]: +> [Denizen]  _/_ _  ._  _ _
[06:43:07] [Server thread/INFO]: +> [Denizen] (/(-/ )/ /_(-/ )  scriptable minecraft 
[06:43:07] [Server thread/INFO]: +> [Denizen] 
[06:43:07] [Server thread/INFO]: +> [Denizen] by: mcmonkey, Morphan1, aufdemrand and others
[06:43:07] [Server thread/INFO]: +> [Denizen] Chat with us at:  https://discord.gg/Q6pZGSR 
[06:43:07] [Server thread/INFO]: +> [Denizen] Or learn more at:  https://denizenscript.com 
[06:43:07] [Server thread/INFO]: +> [Denizen] version: 1.0.5-SNAPSHOT (build 775-DEV) 
[06:43:07] [Server thread/INFO]: +> [Denizen] +-------------------------+
...
[06:43:07] [Server thread/INFO]: ERROR! Unable to register property 'EntityPickupStatus'! 
[06:43:07] [Server thread/INFO]: ERROR! Internal exception was thrown! 
[06:43:07] [Server thread/INFO]: ERROR! 06:43:07 [SEVERE] java.lang.IllegalAccessException: no such method: net.aufdemrand.denizen.objects.properties.entity.EntityPickupStatus.getFrom(dObject)EntityPickupStatus/invokeStatic
06:43:07 [SEVERE] java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:959)
06:43:07 [SEVERE] java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1101)
06:43:07 [SEVERE] java.base/java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:2030)
06:43:07 [SEVERE] java.base/java.lang.invoke.MethodHandles$Lookup.findStatic(MethodHandles.java:1102)
06:43:07 [SEVERE] net.aufdemrand.denizencore.objects.properties.PropertyParser.registerProperty(PropertyParser.java:85)
06:43:07 [SEVERE] net.aufdemrand.denizen.Denizen.onEnable(Denizen.java:858)
06:43:07 [SEVERE] org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
06:43:07 [SEVERE] org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352)
06:43:07 [SEVERE] org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:416)
06:43:07 [SEVERE] org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:458)
06:43:07 [SEVERE] org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:372)
06:43:07 [SEVERE] net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:440)
06:43:07 [SEVERE] net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258)
06:43:07 [SEVERE] net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:758)
06:43:07 [SEVERE] java.base/java.lang.Thread.run(Thread.java:834)
06:43:07 [SEVERE] Caused by: java.lang.NoClassDefFoundError: org/bukkit/entity/Arrow$PickupStatus
06:43:07 [SEVERE] java.base/java.lang.invoke.MethodHandleNatives.resolve(Native Method)
06:43:07 [SEVERE] java.base/java.lang.invoke.MemberName$Factory.resolve(MemberName.java:1070)
06:43:07 [SEVERE] java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1098)
06:43:07 [SEVERE] java.base/java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:2030)
06:43:07 [SEVERE] java.base/java.lang.invoke.MethodHandles$Lookup.findStatic(MethodHandles.java:1102)
06:43:07 [SEVERE] net.aufdemrand.denizencore.objects.properties.PropertyParser.registerProperty(PropertyParser.java:85)
06:43:07 [SEVERE] net.aufdemrand.denizen.Denizen.onEnable(Denizen.java:858)
06:43:07 [SEVERE] org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
06:43:07 [SEVERE] org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352)
06:43:07 [SEVERE] org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:416)
06:43:07 [SEVERE] org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:458)
06:43:07 [SEVERE] org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:372)
06:43:07 [SEVERE] net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:440)
06:43:07 [SEVERE] net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258)
06:43:07 [SEVERE] net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:758)
06:43:07 [SEVERE] java.base/java.lang.Thread.run(Thread.java:834)
06:43:07 [SEVERE] Caused by: java.lang.ClassNotFoundException: org.bukkit.entity.Arrow$PickupStatus
06:43:07 [SEVERE] org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
06:43:07 [SEVERE] org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81)
06:43:07 [SEVERE] java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
06:43:07 [SEVERE] java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
06:43:07 [SEVERE] java.base/java.lang.invoke.MethodHandleNatives.resolve(Native Method)
06:43:07 [SEVERE] java.base/java.lang.invoke.MemberName$Factory.resolve(MemberName.java:1070)
06:43:07 [SEVERE] java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1098)
06:43:07 [SEVERE] java.base/java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:2030)
06:43:07 [SEVERE] java.base/java.lang.invoke.MethodHandles$Lookup.findStatic(MethodHandles.java:1102)
06:43:07 [SEVERE] net.aufdemrand.denizencore.objects.properties.PropertyParser.registerProperty(PropertyParser.java:85)
06:43:07 [SEVERE] net.aufdemrand.denizen.Denizen.onEnable(Denizen.java:858)
06:43:07 [SEVERE] org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
06:43:07 [SEVERE] org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352)
06:43:07 [SEVERE] org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:416)
06:43:07 [SEVERE] org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:458)
06:43:07 [SEVERE] org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:372)
06:43:07 [SEVERE] net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:440)
06:43:07 [SEVERE] net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258)
06:43:07 [SEVERE] net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:758)
06:43:07 [SEVERE] java.base/java.lang.Thread.run(Thread.java:834)
```
Does not occur with Spigot 1.13.2 final.
BTW, it would be nice if Sentinel did more standard error logging:
- timestamps in []
- [Denizen] identified
- [ERROR] instead of, or in addition to [SEVERE]

**Comment by mcmonkey4eva** [comment]
`BTW, it would be nice if Sentinel did more standard error logging:`
Denizen*, and... that's actually just one of the older formats the minecraft server console had. It seems to inexplicably change every version. I've changed the error logger to just not attempt to replicate the format, and instead simply prefix with `[Error Continued]` and the rest stripped.

The lack of `[Denizen]` should be irrelevant as that's a Denizen script error - ie it would only ever appear in the context of a script breaking or Denizen failing to load.

`Spigot 1.14 (2235)` that's not a Spigot version. I don't know what that is.

As for the error: it looks like Spigot changed the arrow API after I reported that spawning arrows was broken. They fixed the problem but then broke other things... naturally...

Will update to function with that shortly

**Comment by mcmonkey4eva** [comment]
Fixed in build 777+

**Comment by mcmonkey4eva** [comment]
This meta-issue is no longer in use.

Most issues are patched, support now targets 1.14.2.
1.14.x itself is not fully stable (due to Mojang having trouble), so most servers should remain on 1.13.2 until more stable Minecraft builds are released.
Some issues do remain present, and should be treated as their own issues rather than stuffing into the meta-issue.
